# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 neroued

"""neroued_3mf — lightweight Python bindings for writing 3MF files."""

from neroued_3mf._neroued_3mf import (
    BBox,
    BaseMaterial,
    BaseMaterialGroup,
    BuildItem,
    Color,
    Component,
    CustomContentType,
    CustomPart,
    CustomRelationship,
    Document,
    DocumentBuilder,
    IOError,
    IndexTriangle,
    InputError,
    Mesh,
    Metadata,
    Object,
    ObjectType,
    ProductionConfig,
    Thumbnail,
    Transform,
    TriangleProperty,
    Unit,
    ValidationResult,
    Vec3f,
    WriteOptions,
    XmlNamespace,
    write_to_buffer,
    write_to_file,
)

__version__ = "0.1.0"

__all__ = [
    "BBox",
    "BaseMaterial",
    "BaseMaterialGroup",
    "BuildItem",
    "Color",
    "Component",
    "CustomContentType",
    "CustomPart",
    "CustomRelationship",
    "Document",
    "DocumentBuilder",
    "IOError",
    "IndexTriangle",
    "InputError",
    "Mesh",
    "Metadata",
    "ObjectType",
    "Object",
    "ProductionConfig",
    "Thumbnail",
    "Transform",
    "TriangleProperty",
    "Unit",
    "ValidationResult",
    "Vec3f",
    "WriteOptions",
    "XmlNamespace",
    "write_to_buffer",
    "write_to_file",
]
